"""Constants for policy engine: actions and semantics."""

ACTION_ALLOW = "allow"
ACTION_BLOCK = "block"
ACTION_REDACT = "redact"
ACTION_MONITOR = "monitor"
ACTION_FLAG = "flag"

ENFORCEMENT_ACTIONS = (ACTION_BLOCK, ACTION_REDACT, ACTION_MONITOR, ACTION_FLAG)

DEFAULT_REDACTION_PLACEHOLDER = "[REDACTED]"
