"""ResourceContract, cgroup detection, dummy pools, SIGHUP reload."""

from gateway_v2.runtime.cgroup import DetectHooks, detect, detect_with_hooks
from gateway_v2.runtime.errors import CapacityUnavailable, CapacityUnset
from gateway_v2.runtime.kinds import CapacityHint, HardwareSignals, PoolKind
from gateway_v2.runtime.lifecycle import install_sighup
from gateway_v2.runtime.pools import DummyPool, GatewayRuntime
from gateway_v2.runtime.resources import ResourceContract, from_signals, load_contract
from gateway_v2.runtime.state_feed import (
    FeedReader,
    FeedRound,
    Head,
    IndexPage,
    StateStore,
)
from gateway_v2.runtime.state_metrics import (
    ABSENT,
    PREFIX,
    SERIES_COUNT,
    EngagedView,
    FreshnessMetrics,
    FreshnessView,
    IdentityMetrics,
    IdentityStats,
    KillSwitchMetrics,
    KindMetrics,
    NudgeMetrics,
    StateMetrics,
    StateMetricsRecorder,
)
from gateway_v2.runtime.state_nudge import (
    DEFAULT_KNOBS,
    ListenerCounters,
    NudgeListener,
    PushKnobs,
    parse_nudge,
)
from gateway_v2.runtime.state_sig import (
    MANIFEST_DOMAIN,
    RECORD_DOMAIN,
    STAMP_DOMAIN,
    canonical_body,
    decode_manifest,
    decode_record,
    decode_stamp,
    encode_manifest,
    encode_record,
    encode_stamp,
    make_manifest,
    make_record,
    make_stamp,
    record_matches_index,
    stamp_millis,
    stamp_signature,
)
from gateway_v2.runtime.state_stamp import (
    FRESHNESS_NOT_ENFORCED,
    NO_STAMP_SEEN,
    RECHECK_S,
    StampView,
    state_ready,
)
from gateway_v2.runtime.state_task import (
    DEFAULT_BUDGET,
    MAX_DRAIN_ROUNDS,
    Applier,
    DeltaBudget,
    RoundReport,
    StateSynchroniser,
)
from gateway_v2.runtime.store_keys import (
    DEFAULT_NAMESPACE,
    ENGAGED_KINDS,
    HASH_KINDS,
    KEYS,
    StoreKeys,
)
from gateway_v2.runtime.store_valkey import (
    UnboundedStoreClient,
    ValkeyStateStore,
    bounded_timeout_s,
    require_bounded_client,
)

__all__ = (
    "ABSENT",
    "DEFAULT_BUDGET",
    "DEFAULT_KNOBS",
    "DEFAULT_NAMESPACE",
    "ENGAGED_KINDS",
    "FRESHNESS_NOT_ENFORCED",
    "HASH_KINDS",
    "KEYS",
    "MANIFEST_DOMAIN",
    "MAX_DRAIN_ROUNDS",
    "NO_STAMP_SEEN",
    "PREFIX",
    "RECHECK_S",
    "RECORD_DOMAIN",
    "SERIES_COUNT",
    "STAMP_DOMAIN",
    "Applier",
    "CapacityHint",
    "CapacityUnavailable",
    "CapacityUnset",
    "DeltaBudget",
    "DetectHooks",
    "DummyPool",
    "EngagedView",
    "FeedReader",
    "FeedRound",
    "FreshnessMetrics",
    "FreshnessView",
    "GatewayRuntime",
    "HardwareSignals",
    "Head",
    "IdentityMetrics",
    "IdentityStats",
    "IndexPage",
    "KillSwitchMetrics",
    "KindMetrics",
    "ListenerCounters",
    "NudgeListener",
    "NudgeMetrics",
    "PoolKind",
    "PushKnobs",
    "ResourceContract",
    "RoundReport",
    "StampView",
    "StateMetrics",
    "StateMetricsRecorder",
    "StateStore",
    "StateSynchroniser",
    "StoreKeys",
    "UnboundedStoreClient",
    "ValkeyStateStore",
    "bounded_timeout_s",
    "canonical_body",
    "decode_manifest",
    "decode_record",
    "decode_stamp",
    "detect",
    "detect_with_hooks",
    "encode_manifest",
    "encode_record",
    "encode_stamp",
    "from_signals",
    "install_sighup",
    "load_contract",
    "make_manifest",
    "make_record",
    "make_stamp",
    "parse_nudge",
    "record_matches_index",
    "require_bounded_client",
    "stamp_millis",
    "stamp_signature",
    "state_ready",
)
