#!/usr/bin/env python3
"""Assert that every file:line cited in the final report contains the expected token.
Read-only. Prints PASS/FAIL per citation and a total."""
import sys

R = "/home/contact_cyberultron_com/AI_Mesh_Firewall/"
C = R + "control/ai_mesh_control/"
G = R + "gateway/ai_mesh_gateway/"
CITES = [
    # --- FirewallConfig
    (C + "main_app/urls.py", 34, "api/firewall/config/"),
    (C + "core/firewall_config_serializer.py", 73, 'exclude = ("id", "updated_by")'),
    (C + "core/firewall_config_serializer.py", 74, "read_only_fields"),
    (C + "core/firewall_config_views.py", 63, "serializer.save(updated_by=request.user)"),
    (C + "core/models.py", 1373, 'f"firewall:config:{slug}"'),
    (C + "core/models.py", 1375, "def build_gateway_payload"),
    (C + "core/signals.py", 404, 'CONFIG_UPDATES_CHANNEL = "config_updates"'),
    (C + "core/signals.py", 407, "@receiver(post_save, sender=FirewallConfig)"),
    (C + "core/signals.py", 424, 'gw_payload["org_slug"] = org_slug'),
    (C + "core/signals.py", 430, "client.set(redis_key, payload)"),
    (C + "core/signals.py", 431, "client.publish(CONFIG_UPDATES_CHANNEL"),
    (C + "core/signals.py", 450, "bump_scan_version(org_slug)"),
    (C + "core/signals.py", 235, "client.set(cfg.build_redis_key(), json.dumps(cfg.build_gateway_payload()))"),
    (C + "core/signals.py", 246, 'client.publish(CONFIG_UPDATES_CHANNEL, json.dumps({"action": "reload"}))'),
    (C + "main_app/settings.py", 497, "core.tasks.reconcile_routing_state"),
    (G + "config_sync.py", 25, 'REDIS_KEY_PREFIX = "firewall:config:"'),
    (G + "config_sync.py", 28, 'PUBSUB_CHANNEL = "config_updates"'),
    (G + "config_sync.py", 174, "return True  # unknown key"),
    (G + "config_sync.py", 480, "raw = await client.get(REDIS_KEY)"),
    (G + "config_sync.py", 487, "self._apply(data)"),
    (G + "config_sync.py", 491, 'client.scan_iter(match=f"{REDIS_KEY_PREFIX}*")'),
    (G + "config_sync.py", 500, "self._config_by_org[slug] = {**self._config, **data}"),
    (G + "config_sync.py", 558, 'log_level_name = data.get("log_level")'),
    (G + "config_sync.py", 598, "await pubsub.subscribe(PUBSUB_CHANNEL)"),
    (G + "config_sync.py", 656, "raw = await client.get(key)"),
    (G + "config_sync.py", 687, "self._config_by_org[org_slug] = {**self._config, **data}"),
    (G + "config_sync.py", 689, "self._apply(data)"),
    (G + "main.py", 7703, "org_config = CONFIG_SYNC.get_config(org_slug)"),
    (G + "main.py", 13522, 'CONFIG.get("rag_default_max_results", 10)'),
    (G + "main.py", 13864, 'CONFIG.get("rag_default_max_results", 10)'),
    (G + "rag_pipeline/retriever_stage.py", 142, 'self._config.get("vector_db_isolation", True)'),
    (G + "mcp_proxy.py", 967, '"mcp_tier2_enabled": data.get("mcp_tier2_enabled")'),
    (G + "mcp_proxy.py", 976, '"mcp_policy_only_enforcement": data.get("mcp_policy_only_enforcement")'),
    (C + "mcp_connector/views.py", 2647, '"mcp_tier2_enabled": mcp_tier2_enabled'),
    (C + "mcp_connector/views.py", 2649, '"mcp_policy_only_enforcement": mcp_policy_only_enforcement'),
    (G + "config.py", 139, "GATEWAY_TIER2_FAIL_CLOSED_ENABLED"),
    (G + "scanner.py", 2461, 'self._config.get("tier2_input_fail_closed", False)'),
    # --- LLM model configs
    (C + "core/llm_model_urls.py", 8, "LLMModelConfigListView"),
    (C + "core/signals.py", 483, 'redis_key = f"llm:model_configs:{slug}"'),
    (C + "core/signals.py", 501, "client.set(redis_key, payload)"),
    (C + "core/signals.py", 504, '"action": "model_reload"'),
    (G + "config_sync.py", 504, 'client.scan_iter(match=f"{LLM_MODEL_CONFIGS_PREFIX}*")'),
    (G + "config_sync.py", 622, 'if action == "model_reload":'),
    (G + "config_sync.py", 718, "raw = await client.get(key)"),
    # --- Policies
    (C + "policy/compiler.py", 32, 'REDIS_KEY_COMPILED = "policies:compiled"'),
    (C + "policy/compiler.py", 34, 'PUBSUB_CHANNEL = "policy_updates"'),
    (C + "policy/compiler.py", 145, "BUNDLE_SCHEMA_VERSION = 2"),
    (C + "policy/compiler.py", 220, '"bundle_schema_version": BUNDLE_SCHEMA_VERSION'),
    (C + "policy/compiler.py", 252, 'redis_key = f"{REDIS_KEY_COMPILED}:{org_slug}"'),
    (C + "policy/compiler.py", 253, 'version_key = f"{REDIS_KEY_VERSION}:{org_slug}"'),
    (C + "policy/compiler.py", 322, 'bundle["version"] = new_version'),
    (C + "policy/compiler.py", 324, "sign_bundle(bundle)"),
    (C + "policy/compiler.py", 344, "pipe.set(version_key, new_version)"),
    (C + "policy/compiler.py", 345, "pipe.set(redis_key, serialized_bundle)"),
    (C + "policy/compiler.py", 346, "pipe.publish(PUBSUB_CHANNEL, notification)"),
    (C + "policy/compiler_signals.py", 92, "@receiver(post_save, sender=Policy)"),
    (C + "policy/compiler_signals.py", 122, "@receiver(post_save, sender=Rule)"),
    (C + "policy/compile_views.py", 110, "success = compiler.push_to_redis("),
    (C + "policy/views.py", 1025, "MCPServerRuleState.objects.update_or_create("),
    (C + "policy/signing.py", 43, 'SIG_ALG = "HMAC-SHA256"'),
    (G + "policy_sync.py", 307, 'client.scan_iter(match=f"{REDIS_KEY_COMPILED}:*"'),
    (G + "policy_sync.py", 117, "if verify_bundle(bundle):"),
    (G + "policy_sync.py", 362, "def _is_newer_notification("),
    (G + "policy_sync.py", 440, "await pubsub.subscribe(PUBSUB_CHANNEL)"),
    (G + "policy_sync.py", 513, "raw_bundle = await client.get(redis_key)"),
    (G + "policy_sync.py", 36, 'REDIS_KEY_VERSION = "policies:version"'),
    (G + "main.py", 6609, 'if CONFIG.get("policy_cache_enabled", True):'),
    (R + "frontend/src/components/PolicyManagementPanel.jsx", 1402, '"/api/policies/compile/"'),
    # --- Vector policies
    (C + "policy/vector_compiler.py", 26, 'REDIS_KEY_COMPILED = "vector:policies:compiled"'),
    (C + "policy/vector_compiler.py", 105, 'lookup_key = f"{policy.organization_id}::{policy.collection_name}"'),
    (C + "policy/vector_compiler.py", 166, 'bundle["version"] = new_version'),
    (C + "policy/vector_compiler.py", 181, "pipe.set(REDIS_KEY_VERSION, new_version)"),
    (C + "policy/vector_compiler.py", 182, "pipe.set(REDIS_KEY_COMPILED, serialized_bundle)"),
    (C + "policy/vector_compiler.py", 183, "pipe.publish(PUBSUB_CHANNEL, notification)"),
    (C + "policy/vector_views.py", 177, "VectorPolicyCompiler().compile_and_push(trigger=trigger)"),
    (C + "policy/vector_signals.py", 85, "@receiver(post_save, sender=VectorCollectionPolicy)"),
    (G + "vector_policy_sync.py", 169, "raw_bundle = await client.get(REDIS_KEY_COMPILED)"),
    (G + "vector_policy_sync.py", 209, "await pubsub.subscribe(PUBSUB_CHANNEL)"),
    (G + "vector_policy_sync.py", 272, "await client.get(REDIS_KEY_COMPILED)"),
    (G + "main.py", 6615, 'if CONFIG.get("rag_enabled", False):'),
    (G + "config.py", 175, "GATEWAY_RAG_ENABLED"),
    # --- Vector providers
    (C + "policy/vector_provider_signals.py", 34, 'REDIS_KEY_PROVIDERS_ORG_PREFIX = "vector:providers:compiled:"'),
    (C + "policy/vector_provider_signals.py", 61, 'client.set(f"{REDIS_KEY_PROVIDERS_ORG_PREFIX}{_org}", json.dumps(_sub))'),
    (C + "policy/vector_provider_signals.py", 73, "client.delete(REDIS_KEY_PROVIDERS_COMPILED)"),
    (C + "policy/vector_provider_signals.py", 81, "client.publish(PUBSUB_CHANNEL, json.dumps(notification))"),
    (C + "policy/vector_provider_signals.py", 95, "@receiver(post_save, sender=VectorProviderConfig)"),
    (G + "vector_provider_sync.py", 113, 'client.scan_iter(match=f"{REDIS_KEY_ORG_PREFIX}*"'),
    (G + "vector_provider_sync.py", 125, "await client.get(REDIS_KEY_COMPILED)"),
    (G + "vector_provider_sync.py", 131, "hashlib.sha256"),
    (G + "vector_provider_sync.py", 154, "await pubsub.subscribe(PUBSUB_CHANNEL)"),
    (G + "main.py", 6653, "VECTOR_PROVIDER_SYNC = VectorProviderSync("),
    # --- Kill switches
    (C + "core/kill_switch_views.py", 205, "instance.save()"),
    (C + "core/kill_switch_views.py", 248, "instance.save()"),
    (C + "core/models.py", 840, 'return f"kill_switch:{prefix}:global"'),
    (C + "core/models.py", 843, 'return f"kill_switch:{prefix}:credential:{credential_prefix}:model:{self.model_name}"'),
    (C + "core/models.py", 844, 'return f"kill_switch:{prefix}:model:{self.model_name}"'),
    (C + "core/signals.py", 279, "@receiver(post_save, sender=KillSwitch)"),
    (C + "core/signals.py", 301, "client.set(redis_key, payload)"),
    (C + "core/signals.py", 308, "client.delete(redis_key)"),
    (C + "core/signals.py", 333, "result = client.delete(redis_key)"),
    (C + "core/redis_kill_switch_views.py", 36, "client.scan_iter("),
    (C + "core/redis_kill_switch_views.py", 138, "client.delete(key)"),
    (G + "kill_switch.py", 65, "pipe.get(redis_key)"),
    (G + "circuit_breaker.py", 140, 'return f"kill_switch:{slug}:model:{model}"'),
    (G + "circuit_breaker.py", 211, "await self._redis.set(key, payload, ex=ttl)"),
    (G + "circuit_breaker.py", 243, 'pattern = f"kill_switch:*:model:{model}"'),
    # --- Gateway API keys
    (C + "core/gateway_urls.py", 20, 'router.register(r"keys", GatewayAPIKeyViewSet'),
    (C + "core/signals.py", 45, 'REDIS_KEY_PREFIX = "auth:apikey:"'),
    (C + "core/signals.py", 77, "@receiver(post_save, sender=GatewayAPIKey)"),
    (C + "core/signals.py", 105, "client.setex(redis_key, ttl_seconds, payload)"),
    (C + "core/signals.py", 111, "client.set(redis_key, payload)"),
    (C + "core/signals.py", 253, "@receiver(post_delete, sender=GatewayAPIKey)"),
    (C + "core/signals.py", 266, "result = client.delete(redis_key)"),
    (C + "core/gateway_key_views.py", 429, "def purge_revoked"),
    (C + "core/gateway_key_views.py", 444, "instance.delete()"),
    (C + "core/gateway_views.py", 262, "GatewayAPIKey.ensure_simulator_for_org(org, actor)"),
    (C + "core/gateway_views.py", 359, "GatewayAPIKey.ensure_isolation_playground_for_org(org, actor)"),
    (C + "core/gateway_views.py", 402, "GatewayAPIKey.rotate_isolation_playground_for_org("),
    (C + "core/gateway_instance_views.py", 89, "def get(self, request: Request):"),
    (C + "core/simulator_seed.py", 127, "ensure_default_llm_model(org)"),
    (C + "main_app/settings.py", 490, "core.tasks.resync_gateway_keys"),
    (G + "middleware.py", 30, 'REDIS_KEY_PREFIX = "auth:apikey:"'),
    (G + "middleware.py", 205, "raw_payload = await redis_client.get(redis_key)"),
    (C + "mcp_connector/views.py", 2861, "GatewayAPIKey.ensure_default_for_org(org, actor)"),
    # --- Model state
    (C + "core/model_state_urls.py", 19, 'path("isolate/", ModelIsolateView'),
    (C + "core/model_state_views.py", 301, "state.save()"),
    (C + "core/model_state_views.py", 365, "state.save()"),
    (C + "core/models.py", 1879, 'return f"model_state:{org_slug}:{self.model_name}"'),
    (C + "core/signals.py", 351, "@receiver(post_save, sender=ModelState)"),
    (C + "core/signals.py", 366, "client.set(redis_key, payload)"),
    (C + "core/signals.py", 393, "client.delete(redis_key)"),
    (G + "model_state.py", 56, "await redis_client.get(key)"),
    (G + "model_state.py", 280, "await redis_client.set(state_key, json.dumps(isolation_payload))"),
    (G + "main.py", 10556, 'f"model_state:{org_slug or \'default\'}:{requested_model}"'),
    # --- Circuit breaker
    (C + "core/gateway_admin_proxy_views.py", 148, '_proxy("POST", "/v1/admin/circuit-breaker-trigger", request.data)'),
    (C + "core/gateway_admin_proxy_views.py", 162, '_proxy("POST", "/v1/admin/circuit-breaker-reset", request.data)'),
    (G + "main.py", 15993, '"/v1/admin/circuit-breaker-trigger"'),
    (G + "main.py", 16016, "await CIRCUIT_BREAKER.record_error(model, error_type)"),
    (G + "main.py", 16027, '"/v1/admin/circuit-breaker-reset"'),
    # --- MCP connector
    (C + "mcp_connector/signals.py", 40, 'SCAN_VER_KEY_PREFIX = "mcp:scan_ver"'),
    (C + "mcp_connector/signals.py", 99, "version = _get_redis_client().incr(key)"),
    (C + "mcp_connector/signals.py", 203, "@receiver(post_save, sender=MCPScanControl)"),
    (C + "mcp_connector/views.py", 410, "/v1/mcp/internal/oauth-token-mirror"),
    (C + "mcp_connector/views.py", 802, "/v1/mcp/internal/discover-tools"),
    (C + "mcp_connector/views.py", 2535, "class MCPGatewayEnabledToolsView"),
    (G + "mcp_proxy.py", 678, "await client.mget("),
    (G + "mcp_proxy.py", 759, "/api/mcp-connector/servers/"),
    (G + "mcp_proxy.py", 927, "/api/mcp-connector/internal/enabled-tools/"),
    (G + "mcp_proxy.py", 1262, 'cfg.get("mcp_ext_scan_action")'),
    (G + "mcp_proxy.py", 3667, '"/internal/oauth-token-mirror"'),
    (G + "mcp_oauth_proxy.py", 108, 'return f"mcp:oauth:token:{org_slug}|{server_url}"'),
    # --- /api/mcp/*
    (R + "deploy/nginx.conf", 92, 'set $control_upstream "control:8000"'),
    (R + "frontend/src/components/MCPManagerPanel.jsx", 240, '"/api/mcp/servers/"'),
    # --- reverse-direction / non-config
    (C + "core/ingestion_views.py", 209, "redis_client.rpush(REDIS_TELEMETRY_KEY"),
    (G + "main.py", 16838, 'REDIS_CLIENT.llen("telemetry:events")'),
    (C + "main_app/settings.py", 1008, "RedisLogPublisher"),
    (R + "shared/ai_mesh_shared/redis_log_handler.py", 100, "client.publish(self._channel"),
    (G + "log_buffer.py", 180, "subscribe(self._channel)"),
    (G + "mcp_error_classifier.py", 48, '_DIAG_PREFIX = "mcp:diag:"'),
    (G + "jobs.py", 56, "client.lpush(GATEWAY_JOBS_QUEUE"),
    # --- added round 2
    (G + "config_sync.py", 714, "keys_to_check.append(LLM_MODEL_CONFIGS_REDIS_KEY)"),
    (G + "config_sync.py", 625, "await self._refresh(client, org_slug=org_slug)"),
    (G + "config_sync.py", 620, 'org_slug = parsed.get("org_slug", "")'),
    (G + "config_sync.py", 655, "key = REDIS_KEY"),
    (G + "mcp_error_classifier.py", 223, 'f"{_DIAG_PREFIX}{ref}"'),
    (C + "mcp_connector/views.py", 681, "raw = client.get(_diag_cache_key(ref))"),
    (C + "core/tasks.py", 946, "client.lrange(REDIS_GATEWAY_JOBS_KEY"),
    (G + "telemetry.py", 128, "pipe.lpush(REDIS_TELEMETRY_KEY, item)"),
    (C + "policy/evaluation_views.py", 1081, "def get(self, request: Request):"),
    (C + "policy/compile_views.py", 176, "raw_bundle = client.get(redis_key)"),
    (G + "policy_sync.py", 198, 'server_states = policy.get("server_states") or {}'),
    (C + "core/model_state_bootstrap.py", 58, "ModelState.objects.get_or_create("),
    (C + "core/management/commands/resync_kill_switches.py", 41, "client.set(key"),
    (C + "core/signals.py", 241, "client.set(st.build_redis_key(), json.dumps(st.build_redis_payload()))"),
    (C + "core/signals.py", 124, "def resync_all_gateway_keys"),
    (C + "core/signals.py", 546, "@receiver(post_save, sender=LLMModelConfig)"),
    (C + "core/signals.py", 567, "@receiver(post_delete, sender=LLMModelConfig)"),
    (C + "core/firewall_config_views.py", 56, "serializer = FirewallConfigSerializer("),
    (C + "core/firewall_config_views.py", 58, "data=request.data"),
    (C + "policy/tasks.py", 21, '@shared_task(name="policy.compile_policies")'),
    (R + "docker-compose.yml", 178, 'profiles: ["workers"]'),
    (G + "vector_policy_sync.py", 21, 'REDIS_KEY_VERSION = "vector:policies:version"'),
    (G + "vector_policy_sync.py", 231, "if incoming_version == self._version:"),
    (G + "vector_routes.py", 355, "auth:apikey:{key_hash}"),
    (G + "middleware.py", 202, 'redis_key = f"{REDIS_KEY_PREFIX}{key_hash}"'),
    (G + "main.py", 12485, "REDIS_CLIENT.scan_iter("),
    (G + "main.py", 10731, 'ms_key = f"model_state:'),
    (G + "circuit_breaker.py", 152, "await self._redis.get(state_key)"),
    (G + "model_state.py", 90, "await redis_client.set(key, json.dumps(healed))"),
    (G + "model_state.py", 332, "await redis_client.set(state_key, json.dumps(recovery_payload))"),
    (G + "main.py", 16050, 'match=f"circuit:*:{model}*"'),
]
fails = 0
for path, ln, tok in CITES:
    try:
        line = open(path, encoding="utf-8", errors="replace").read().splitlines()[ln - 1]
    except Exception as e:  # noqa: BLE001
        line = f"<<{e}>>"
    ok = tok in line
    fails += not ok
    print(f"{'PASS' if ok else 'FAIL'} {path.replace(R, '')}:{ln}  token={tok!r}" + ("" if ok else f"\n      actual: {line.strip()[:160]}"))
print(f"\nTOTAL {len(CITES)}  PASS {len(CITES) - fails}  FAIL {fails}")
