# Generated by Django 6.0.5 on 2026-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_terminatedsession_cleared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_platform_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
