# Generated by Django 6.0.1 - Phase 1 Agent Registry

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("browser", "Browser"),
                            ("desktop", "Desktop"),
                            ("ide", "IDE"),
                            ("mobile", "Mobile"),
                            ("api", "API"),
                            ("gateway", "Gateway"),
                            ("mcp", "MCP"),
                            ("agentic", "Agentic"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("restricted", "Restricted"), ("suspended", "Suspended")],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="core.endpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
