# Generated by Django 6.0.2 on 2026-02-13 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_agent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayAPIKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="First 8 characters of the plaintext key (for identification in logs).",
                        max_length=8,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA-256 hex digest of the full API key.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable label (e.g. 'prod-rag-service').", max_length=128)),
                (
                    "project_id",
                    models.CharField(
                        db_index=True,
                        help_text="Associated project or tenant identifier for RBAC and billing.",
                        max_length=128,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RBAC Payload (e.g. {'allowed_actions': ['chat', 'embedding'], 'denied_actions': ['fine-tuning']}).",
                    ),
                ),
                (
                    "allowed_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Model allowlist (e.g. ['gpt-4', 'gpt-3.5-turbo']). Empty means no restrictions.",
                    ),
                ),
                (
                    "rate_limit_tokens_per_minute",
                    models.PositiveIntegerField(default=100000, help_text="Rate limit in Tokens Per Minute (TPM)."),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0, help_text="Baseline risk score (0.0 = trusted, 1.0 = highest risk)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, help_text="Soft-disable without deletion."),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiry timestamp. Gateway rejects expired keys.", null=True
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Updated asynchronously on each Gateway validation.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who created / is responsible for this API key.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway API Key",
                "verbose_name_plural": "Gateway API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
