# Generated by Django 6.0.2 on 2026-02-13 06:02

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gatewayapikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatewayapikey",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=core.models._default_permissions,
                help_text="RBAC Payload (e.g. {'allowed_actions': ['chat', 'embedding'], 'denied_actions': ['fine-tuning']}).",
            ),
        ),
        migrations.AlterField(
            model_name="gatewayapikey",
            name="risk_score",
            field=models.FloatField(
                default=0.0,
                help_text="Baseline risk score (0.0 = trusted, 1.0 = highest risk).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
