# Generated by Django 6.0.2 on 2026-02-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_gatewayapikey_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewayapikey",
            name="max_context_tokens",
            field=models.PositiveIntegerField(default=0, help_text="Max context tokens per request. 0 = unlimited."),
        ),
        migrations.AddField(
            model_name="gatewayapikey",
            name="mcp_allowed_tools",
            field=models.JSONField(
                blank=True, default=list, help_text="MCP tool allowlist. Empty = all tools allowed."
            ),
        ),
        migrations.AddField(
            model_name="gatewayapikey",
            name="mcp_max_tool_calls",
            field=models.PositiveIntegerField(default=0, help_text="Max MCP tool calls per turn. 0 = unlimited."),
        ),
    ]
