# Generated by Django 6.0.2 on 2026-02-25 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_gatewayapikey_max_context_tokens_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KillSwitch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name to kill, or '__global__' for all models.", max_length=255, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[("disable", "Disable"), ("reroute", "Reroute")], default="disable", max_length=20
                    ),
                ),
                (
                    "fallback_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fallback model for 'reroute' action. Ignored for 'disable'.",
                        max_length=255,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kill_switches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kill Switch",
                "verbose_name_plural": "Kill Switches",
                "ordering": ["-updated_at"],
            },
        ),
    ]
