# Generated by Django 6.0.2 on 2026-02-25 14:20

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_killswitch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "firewall_enabled",
                    models.BooleanField(default=True, help_text="Master switch for all firewall enforcement."),
                ),
                (
                    "enforcement_mode",
                    models.CharField(
                        choices=[("block", "Block"), ("monitor", "Monitor"), ("audit", "Audit")],
                        default="block",
                        help_text="How the firewall handles policy violations.",
                        max_length=16,
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("minimal", "Minimal"),
                            ("standard", "Standard"),
                            ("detailed", "Detailed"),
                            ("verbose", "Verbose"),
                        ],
                        default="detailed",
                        help_text="Detail level for security logs.",
                        max_length=16,
                    ),
                ),
                ("rate_limit_enabled", models.BooleanField(default=True, help_text="Protect against abuse and DDoS.")),
                (
                    "requests_per_minute",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Maximum requests allowed per minute (global).",
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                (
                    "burst_limit",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="Maximum requests in a short burst.",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                (
                    "content_filtering_enabled",
                    models.BooleanField(default=True, help_text="Scan and filter sensitive content."),
                ),
                (
                    "pii_detection_enabled",
                    models.BooleanField(
                        default=True, help_text="Detect and redact personally identifiable information."
                    ),
                ),
                (
                    "toxicity_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Minimum score to flag toxic content (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "blocked_keywords",
                    models.TextField(
                        blank=True,
                        default="password, secret, api_key, token",
                        help_text="Comma-separated list of keywords to block.",
                    ),
                ),
                (
                    "model_isolation_enabled",
                    models.BooleanField(default=True, help_text="Enforce strict model boundaries."),
                ),
                (
                    "allowed_models",
                    models.TextField(
                        blank=True,
                        default="gpt-4, gpt-3.5-turbo, claude-3",
                        help_text="Comma-separated list of approved models.",
                    ),
                ),
                (
                    "default_model",
                    models.CharField(default="gpt-4", help_text="Fallback model when none specified.", max_length=64),
                ),
                (
                    "jailbreak_detection_enabled",
                    models.BooleanField(default=True, help_text="Detect and block jailbreak attempts."),
                ),
                (
                    "semantic_analysis_enabled",
                    models.BooleanField(default=True, help_text="Deep analysis of prompt intent (Tier-2 ML scanning)."),
                ),
                (
                    "prompt_injection_threshold",
                    models.FloatField(
                        default=0.8,
                        help_text="Sensitivity for injection detection (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "response_filtering_enabled",
                    models.BooleanField(default=True, help_text="Scan and filter model responses."),
                ),
                (
                    "factuality_check_enabled",
                    models.BooleanField(default=False, help_text="Verify response accuracy (hallucination check)."),
                ),
                (
                    "max_response_tokens",
                    models.PositiveIntegerField(
                        default=4096,
                        help_text="Maximum tokens in model response.",
                        validators=[django.core.validators.MaxValueValidator(32000)],
                    ),
                ),
                ("rag_enabled", models.BooleanField(default=True, help_text="Enable Retrieval-Augmented Generation.")),
                (
                    "vector_db_isolation",
                    models.BooleanField(default=True, help_text="Enforce tenant isolation in vector databases."),
                ),
                (
                    "rag_max_documents",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum documents to retrieve.",
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "rag_relevance_threshold",
                    models.FloatField(
                        default=0.75,
                        help_text="Minimum similarity score for retrieval (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "threat_intel_enabled",
                    models.BooleanField(default=True, help_text="Integrate with threat intelligence feeds."),
                ),
                (
                    "auto_block_threats",
                    models.BooleanField(default=True, help_text="Automatically block known threat actors."),
                ),
                (
                    "threat_score_threshold",
                    models.PositiveIntegerField(
                        default=75,
                        help_text="Minimum score to trigger blocking (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "audit_logging_enabled",
                    models.BooleanField(default=True, help_text="Comprehensive audit trail for compliance."),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="How long to retain audit logs (days).",
                        validators=[django.core.validators.MaxValueValidator(365)],
                    ),
                ),
                (
                    "compliance_frameworks",
                    models.JSONField(
                        blank=True,
                        default=core.models._default_compliance_frameworks,
                        help_text="Active compliance frameworks (e.g. ['SOC2', 'ISO27001']).",
                    ),
                ),
                ("alerting_enabled", models.BooleanField(default=True, help_text="Send alerts for security events.")),
                (
                    "critical_alert_threshold",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Risk score to trigger critical alerts (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "alert_recipients",
                    models.TextField(
                        blank=True,
                        default="security-team@company.com",
                        help_text="Email addresses for security alerts.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firewall_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firewall Configuration",
                "verbose_name_plural": "Firewall Configuration",
            },
        ),
    ]
