# Generated by Django 6.0.2 on 2026-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_firewallconfig_tier2_fail_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMModelConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("azure", "Azure OpenAI"),
                            ("google", "Google AI"),
                            ("aws_bedrock", "AWS Bedrock"),
                            ("ollama", "Ollama (Local)"),
                            ("custom", "Custom / Other"),
                        ],
                        help_text="LLM provider (e.g. openai, anthropic, azure).",
                        max_length=32,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="User-facing model name used in API requests (e.g. gpt-4o).",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="LiteLLM model identifier (e.g. openai/gpt-4o, anthropic/claude-3-opus-20240229).",
                        max_length=256,
                    ),
                ),
                (
                    "api_key_env_var",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Environment variable name for the API key (e.g. OPENAI_API_KEY).",
                        max_length=128,
                    ),
                ),
                (
                    "api_base",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom API base URL (for Ollama, Azure, or self-hosted endpoints).",
                        max_length=512,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", help_text="Cloud region (for AWS Bedrock, Azure, etc.).", max_length=64
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Only active models are routed by the gateway."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Model Configuration",
                "verbose_name_plural": "LLM Model Configurations",
                "ordering": ["provider", "model_name"],
            },
        ),
    ]
