# Generated by Django 6.0.2 on 2026-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_llmmodelconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodelconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("azure", "Azure OpenAI"),
                    ("google", "Google AI"),
                    ("aws_bedrock", "AWS Bedrock"),
                    ("mistral", "Mistral AI"),
                    ("cohere", "Cohere"),
                    ("deepseek", "DeepSeek"),
                    ("huggingface", "Hugging Face"),
                    ("meta", "Meta / Llama"),
                    ("ollama", "Ollama (Local)"),
                    ("custom", "Custom / Other"),
                ],
                help_text="LLM provider (e.g. openai, anthropic, azure).",
                max_length=32,
            ),
        ),
    ]
