# Generated by Django 6.0.2 on 2026-03-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizationagentkey'),
        ('core', '0010_alter_llmmodelconfig_provider'),
    ]

    operations = [
    ]
