# Generated by Django 6.0.3 on 2026-03-19 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_backfill_default_organization'),
        ('core', '0011_merge_20260310_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_configs', to='auth_api.organization', unique=True),
        ),
        migrations.AddField(
            model_name='gatewayapikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_api_keys', to='auth_api.organization'),
        ),
        migrations.AddField(
            model_name='killswitch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kill_switches', to='auth_api.organization'),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='compliance_tags',
            field=models.JSONField(blank=True, default=list, help_text='Compliance frameworks this model meets (e.g. ["SOC2", "HIPAA"]).'),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='cost_per_1k_input_tokens',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost per 1K input tokens (USD).', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='cost_per_1k_output_tokens',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost per 1K output tokens (USD).', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='data_sensitivity_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='public', help_text='Max data sensitivity this model is approved for.', max_length=32),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='latency_sla_ms',
            field=models.PositiveIntegerField(default=30000, help_text='Latency SLA in milliseconds.'),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_model_configs', to='auth_api.organization'),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='rate_limit_rpm',
            field=models.PositiveIntegerField(default=0, help_text='Per-model requests per minute limit. 0 = no per-model limit.'),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Model risk score (0.0=safe, 1.0=highest risk). Updated from telemetry.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='llmmodelconfig',
            name='routing_priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher = preferred for auto-routing.'),
        ),
        migrations.AlterField(
            model_name='killswitch',
            name='model_name',
            field=models.CharField(help_text="Model name to kill, or '__global__' for all models.", max_length=255),
        ),
        migrations.AlterField(
            model_name='llmmodelconfig',
            name='model_name',
            field=models.CharField(help_text='User-facing model name used in API requests (e.g. gpt-4o).', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='killswitch',
            unique_together={('organization', 'model_name')},
        ),
        migrations.AlterUniqueTogether(
            name='llmmodelconfig',
            unique_together={('organization', 'model_name')},
        ),
    ]
