# Generated by Django 6.0.3 on 2026-03-28 04:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_unique_user_email'),
        ('core', '0014_firewallconfig_routing_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitchAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, help_text='Event type, e.g. kill_switch_triggered, model_isolated, auto_recovery.', max_length=64)),
                ('model_name', models.CharField(max_length=255)),
                ('risk_score', models.FloatField(default=0.0)),
                ('threshold', models.FloatField(default=0.0)),
                ('action', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.CharField(blank=True, default='', help_text='system / user email / auto_recovery', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_switch_audit_logs', to='auth_api.organization')),
            ],
            options={
                'verbose_name': 'Kill-Switch Audit Log',
                'verbose_name_plural': 'Kill-Switch Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('isolated', 'Isolated'), ('degraded', 'Degraded')], db_index=True, default='active', max_length=20)),
                ('risk_score', models.FloatField(default=0.0, help_text='Rolling weighted risk score (0–100).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('threshold', models.FloatField(default=80.0, help_text='Risk score threshold that triggers isolation.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('action', models.CharField(choices=[('block', 'Block'), ('reroute', 'Reroute'), ('alert', 'Alert Only')], default='block', help_text='Action to take when threshold is exceeded.', max_length=20)),
                ('fallback_model', models.CharField(blank=True, default='', help_text='Fallback model for reroute action.', max_length=255)),
                ('rolling_window', models.JSONField(blank=True, default=list, help_text='Last N risk signal snapshots for rolling average.')),
                ('isolation_reason', models.TextField(blank=True, default='')),
                ('isolated_at', models.DateTimeField(blank=True, null=True)),
                ('isolated_until', models.DateTimeField(blank=True, null=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Cooldown period in seconds before auto-recovery.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_states', to='auth_api.organization')),
            ],
            options={
                'verbose_name': 'Model State',
                'verbose_name_plural': 'Model States',
                'ordering': ['model_name'],
                'unique_together': {('organization', 'model_name')},
            },
        ),
    ]
