# Generated by Django 6.0.3 on 2026-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organizationupstreamca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.CharField(blank=True, default='', max_length=256)),
                ('contact', models.CharField(blank=True, default='', max_length=256)),
                ('poc_date', models.CharField(blank=True, default='', max_length=64)),
                ('raw_data', models.JSONField(default=dict)),
                ('s3_key', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'POC Submission',
                'verbose_name_plural': 'POC Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
