# Generated by Django 6.0.3 on 2026-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_poc_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocsubmission',
            name='source',
            field=models.CharField(choices=[('ai-mesh', 'AI Mesh Firewall'), ('aiguardx', 'AIGuardX')], db_index=True, default='ai-mesh', max_length=50),
        ),
    ]
