# Generated by Django 6.0.5 on 2026-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_modelstate_data_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallconfig',
            name='output_hallucination_action',
            field=models.CharField(choices=[('block', 'Block'), ('redact', 'Redact'), ('rewrite', 'Rewrite'), ('flag', 'Flag'), ('allow', 'Allow')], default='flag', help_text='Action applied when hallucination risk is detected. Enable toggle is `factuality_check_enabled`; threshold is `hallucination_grounding_threshold`.', max_length=16),
        ),
    ]
