# Generated by Django 6.0.5 on 2026-06-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_firewallconfig_org_tpm_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallconfig',
            name='alert_recipients',
        ),
        migrations.RemoveField(
            model_name='firewallconfig',
            name='alerting_enabled',
        ),
        migrations.RemoveField(
            model_name='firewallconfig',
            name='critical_alert_threshold',
        ),
    ]
