# Generated by Django 6.0.5 on 2026-06-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_gatewayapikey_ueba_v2_fields"),
        ("core", "0034_remove_firewallconfig_alert_recipients_and_more"),
    ]

    operations = []
