# Generated by Django 6.0.5 on 2026-06-29 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20260629_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayapikey',
            name='key_purpose',
            field=models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('simulator', 'Simulator'), ('scanner', 'Scanner')], db_index=True, default='production', max_length=16),
        ),
        migrations.AlterField(
            model_name='gatewayapikey',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Unified UEBA final risk score (0.0 = trusted, 1.0 = highest risk). Written by scoring engine.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
