package rv

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"

	"rvharness/shared"
)

// Words holds the shared word lists (shared/words.json, generated by gen_words.py).
type Words struct {
	Out      []string `json:"out_tokens"`  // provider output tokens, 1 token per SSE chunk
	Nonce    []string `json:"nonce_words"` // 256-word nonce alphabet (PG2 token count verified stable)
	OutB     [][]byte `json:"-"`           // Out as byte slices (no per-chunk conversion/allocation)
	nonceIdx map[string]int
}

// LoadWords parses the embedded words.json.
func LoadWords() (*Words, error) {
	var w Words
	if err := json.Unmarshal(shared.WordsJSON, &w); err != nil {
		return nil, err
	}
	if len(w.Nonce) != 256 || len(w.Out) == 0 {
		return nil, fmt.Errorf("words.json: need 256 nonce words (got %d) and output tokens (got %d)", len(w.Nonce), len(w.Out))
	}
	for _, t := range w.Out {
		w.OutB = append(w.OutB, []byte(t))
	}
	w.nonceIdx = make(map[string]int, 256)
	for i, s := range w.Nonce {
		w.nonceIdx[s] = i
	}
	return &w, nil
}

// FNV1a64 is 64-bit FNV-1a over the UTF-8 bytes of s (mirrored in analyze.py).
func FNV1a64(s string) uint64 {
	h := uint64(14695981039346656037)
	for i := 0; i < len(s); i++ {
		h ^= uint64(s[i])
		h *= 1099511628211
	}
	return h
}

// SplitMix64 is the splitmix64 finalizer (mirrored in analyze.py). It is a bijection on uint64.
func SplitMix64(x uint64) uint64 {
	x += 0x9E3779B97F4A7C15
	x = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9
	x = (x ^ (x >> 27)) * 0x94D049BB133111EB
	return x ^ (x >> 31)
}

// Token returns output token j (0-based) of the deterministic content for content key.
// Content for request r = concat_j Out[SplitMix64(FNV1a64(key)+j) % len(Out)].
func (w *Words) Token(keyHash uint64, j int) string {
	return w.Out[SplitMix64(keyHash+uint64(j))%uint64(len(w.Out))]
}

// TokenB is Token without allocation.
func (w *Words) TokenB(keyHash uint64, j int) []byte {
	return w.OutB[SplitMix64(keyHash+uint64(j))%uint64(len(w.OutB))]
}

// NonceText renders the per-request nonce. Format MUST match gen_words.py nonce_text():
// "(ref-" + w0 + "-" + ... + "-" + w5 + ")" with w0=run tag, w1=loadgen index, w2..w5 = seq
// big-endian bytes. Every nonce is exactly the same number of PG2 tokens (verified: 15).
func (w *Words) NonceText(runTag, lg uint8, seq uint32) string {
	var b strings.Builder
	b.Grow(64)
	b.WriteString("(ref-")
	for i, idx := range [6]byte{runTag, lg, byte(seq >> 24), byte(seq >> 16), byte(seq >> 8), byte(seq)} {
		if i > 0 {
			b.WriteByte('-')
		}
		b.WriteString(w.Nonce[idx])
	}
	b.WriteByte(')')
	return b.String()
}

// FindNonce returns the first well-formed nonce "(ref-a-b-c-d-e-f)" in text whose six words
// are all in the alphabet, or "".
func (w *Words) FindNonce(text []byte) string {
	s := text
	for {
		i := indexBytes(s, "(ref-")
		if i < 0 {
			return ""
		}
		s = s[i:]
		j := 5
		words := 0
		ok := true
		for words < 6 {
			k := j
			for k < len(s) && s[k] >= 'a' && s[k] <= 'z' {
				k++
			}
			if k == j || k >= len(s) {
				ok = false
				break
			}
			if _, found := w.nonceIdx[string(s[j:k])]; !found {
				ok = false
				break
			}
			words++
			if words < 6 {
				if s[k] != '-' {
					ok = false
					break
				}
				j = k + 1
			} else {
				if s[k] != ')' {
					ok = false
					break
				}
				return string(s[:k+1])
			}
		}
		if !ok {
			s = s[1:]
		}
	}
}

func indexBytes(s []byte, sep string) int {
	return strings.Index(unsafeString(s), sep)
}

// RIDFromNonce derives the request id (UUIDv4 layout) from the nonce: sha256(nonce)[:16].
// olg sends it as x-request-id; synthprov recomputes it from the prompt when a gateway does not
// forward the header, so client and provider records always join.
func RIDFromNonce(nonce string) string {
	h := sha256.Sum256([]byte(nonce))
	h[6] = (h[6] & 0x0f) | 0x40
	h[8] = (h[8] & 0x3f) | 0x80
	var out [36]byte
	hex.Encode(out[0:8], h[0:4])
	out[8] = '-'
	hex.Encode(out[9:13], h[4:6])
	out[13] = '-'
	hex.Encode(out[14:18], h[6:8])
	out[18] = '-'
	hex.Encode(out[19:23], h[8:10])
	out[23] = '-'
	hex.Encode(out[24:36], h[10:16])
	return string(out[:])
}

// Sampled reports whether rid is in the deterministic per-chunk-timing sample:
// FNV1a64(rid) % mod == 0 (same rule in olg, synthprov and analyze.py).
func Sampled(rid string, mod uint64) bool {
	return mod > 0 && FNV1a64(rid)%mod == 0
}

// AppendJSONString appends s as the CONTENT of a JSON string (no surrounding quotes).
func AppendJSONString[T string | []byte](dst []byte, s T) []byte {
	const hexd = "0123456789abcdef"
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			dst = append(dst, '\\', '"')
		case c == '\\':
			dst = append(dst, '\\', '\\')
		case c == '\n':
			dst = append(dst, '\\', 'n')
		case c == '\r':
			dst = append(dst, '\\', 'r')
		case c == '\t':
			dst = append(dst, '\\', 't')
		case c < 0x20:
			dst = append(dst, '\\', 'u', '0', '0', hexd[c>>4], hexd[c&0xf])
		default:
			dst = append(dst, c)
		}
	}
	return dst
}
