# Generated by Django 6.0 for policy app

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(help_text="Unique identifier (e.g. POL001)", max_length=64, unique=True)),
                ("category", models.CharField(blank=True, max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[("CRITICAL", "Critical"), ("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=0, help_text="Higher = evaluated first")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "code"],
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("regex", "Regex"), ("keywords", "Keywords"), ("pattern", "Pattern")],
                        default="keywords",
                        max_length=32,
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        default=dict, help_text='e.g. {"regex": "...", "keywords": [...], "field": "prompt"}'
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("block", "Block"), ("redact", "Redact"), ("monitor", "Monitor")],
                        default="block",
                        max_length=16,
                    ),
                ),
                (
                    "redaction_config",
                    models.JSONField(blank=True, default=dict, help_text="For redact: replacement text, patterns"),
                ),
                ("priority", models.PositiveIntegerField(default=0, help_text="Higher = evaluated first")),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="policy.policy"
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "-priority", "id"],
            },
        ),
    ]
