# Generated by Django 6.0.1 - Phase 1 Agent Registry

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_agent"),
        ("policy", "0003_policy_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="enforcementevent",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enforcement_events",
                to="core.agent",
            ),
        ),
    ]
