# Generated by Django 6.0.2 on 2026-02-23 06:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0004_enforcementevent_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorCollectionPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Human-readable policy label.", max_length=255)),
                (
                    "project_id",
                    models.CharField(
                        db_index=True, help_text="Tenant identifier (matches GatewayAPIKey.project_id).", max_length=128
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical collection name (namespaced by project_id at runtime).",
                        max_length=255,
                    ),
                ),
                (
                    "vector_db_type",
                    models.CharField(
                        choices=[("chroma", "ChromaDB"), ("pinecone", "Pinecone"), ("milvus", "Milvus")],
                        default="chroma",
                        max_length=32,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sub-namespace within collection (Pinecone/Milvus partition key).",
                        max_length=255,
                    ),
                ),
                (
                    "default_action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny"), ("monitor", "Monitor")],
                        default="deny",
                        max_length=16,
                    ),
                ),
                (
                    "allowed_operations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Permitted operations, e.g. ["query", "insert", "update", "delete"].',
                    ),
                ),
                (
                    "max_results_per_query",
                    models.PositiveIntegerField(default=10, help_text="Maximum documents returned per query."),
                ),
                (
                    "max_query_length",
                    models.PositiveIntegerField(default=2000, help_text="Maximum characters in query text."),
                ),
                (
                    "sensitive_fields",
                    models.JSONField(
                        blank=True, default=list, help_text="Document metadata fields to scan for PII before returning."
                    ),
                ),
                (
                    "require_context_scan",
                    models.BooleanField(
                        default=True, help_text="Scan retrieved documents for indirect prompt injection."
                    ),
                ),
                (
                    "block_sensitive_documents",
                    models.BooleanField(
                        default=True, help_text="Block documents containing PII/secrets from retrieval results."
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required embedding model for this collection.",
                        max_length=128,
                    ),
                ),
                (
                    "embedding_dimension",
                    models.PositiveIntegerField(
                        blank=True, help_text="Expected embedding vector dimension.", null=True
                    ),
                ),
                (
                    "anomaly_distance_threshold",
                    models.FloatField(
                        default=0.85,
                        help_text="Cosine distance threshold; results above this are flagged as anomalous.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vector Collection Policy",
                "verbose_name_plural": "Vector Collection Policies",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project_id", "collection_name", "vector_db_type"), name="unique_project_collection_vdb"
                    )
                ],
            },
        ),
    ]
