# Generated by Django 6.0.2 on 2026-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_enforcementevent_status_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
