# Generated by Django 6.0.2 on 2026-03-01 08:14
#
# NOTE: Historically this migration added `policy.is_system`. The same column
# is also added by 0006_policy_is_system on the parallel branch, and the two
# branches are reconciled by 0012_merge_20260310_0747. Applying both AddFields
# raises ProgrammingError ("column already exists"). This migration is now a
# no-op so the merge graph still resolves cleanly without re-adding the column.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0008_complianceviolation"),
    ]

    operations = []
