# Generated by Django 6.0.2 on 2026-03-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_policy_is_system'),
        ('policy', '0011_backfill_policy_organization'),
    ]

    operations = [
    ]
