# Generated by Django 6.0.3 on 2026-03-24 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_unique_user_email'),
        ('policy', '0016_policy_policy_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('chroma', 'ChromaDB'), ('pinecone', 'Pinecone'), ('milvus', 'Milvus')], help_text='Vector database provider (chroma, pinecone, milvus).', max_length=32)),
                ('display_name', models.CharField(blank=True, default='', help_text='Human-readable label for this provider configuration.', max_length=128)),
                ('connection_url', models.CharField(blank=True, default='', help_text='Connection URL (e.g. http://localhost:8000 for ChromaDB, URI for Milvus).', max_length=512)),
                ('api_key', models.CharField(blank=True, default='', help_text='Provider API key (Pinecone API key, Milvus token, etc.). Stored encrypted at rest.', max_length=512)),
                ('environment', models.CharField(blank=True, default='', help_text="Provider environment (e.g. Pinecone environment like 'us-east-1').", max_length=128)),
                ('embedding_model', models.CharField(blank=True, default='text-embedding-3-small', help_text='Default embedding model for this provider.', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this provider config is active.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific settings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_provider_configs', to='auth_api.organization')),
            ],
            options={
                'verbose_name': 'Vector Provider Config',
                'verbose_name_plural': 'Vector Provider Configs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider_type'), name='unique_org_vector_provider')],
            },
        ),
    ]
