# Generated by Django 6.0.3 on 2026-03-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_connector', '0003_rename_mcp_connect_organiz_idx_mcp_connect_organiz_b15f69_idx_and_more'),
        ('policy', '0018_mcp_structured_policies'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcppolicyaudit',
            name='policy_mcp_audit_org_ts',
        ),
        migrations.RemoveIndex(
            model_name='mcppolicyaudit',
            name='policy_mcp_audit_req_id',
        ),
        migrations.RemoveIndex(
            model_name='mcppolicyaudit',
            name='policy_mcp_audit_action_ts',
        ),
        migrations.RemoveField(
            model_name='mcpriskcomponent',
            name='organization',
        ),
        migrations.RemoveIndex(
            model_name='mcpstructuredpolicy',
            name='policy_mcp_org_enabled_priority',
        ),
        migrations.RemoveIndex(
            model_name='mcpstructuredpolicy',
            name='policy_mcp_org_type',
        ),
        migrations.AddField(
            model_name='policy',
            name='mcp_server',
            field=models.ForeignKey(blank=True, help_text='Optional: bind this policy to a specific MCP server (MCP-domain only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='mcp_connector.mcpserverregistration'),
        ),
        migrations.RemoveField(
            model_name='mcppolicyaudit',
            name='organization',
        ),
        migrations.DeleteModel(
            name='MCPRiskComponent',
        ),
        migrations.RemoveField(
            model_name='mcpstructuredpolicy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mcpstructuredpolicy',
            name='organization',
        ),
        migrations.DeleteModel(
            name='MCPPolicyAudit',
        ),
        migrations.DeleteModel(
            name='MCPStructuredPolicy',
        ),
    ]
