# Generated by Django 6.0.3 on 2026-03-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0019_remove_mcppolicyaudit_policy_mcp_audit_org_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='target_tool',
            field=models.CharField(blank=True, db_index=True, default='', help_text='MCP tool name this rule targets (empty = all tools). Only used for MCP-domain policies.', max_length=255),
        ),
    ]
