# Generated by Django 6.0.5 on 2026-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0031_remove_global_policy_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorproviderconfig',
            name='connection_url',
            field=models.CharField(blank=True, default='', help_text='Connection URL (e.g. URI for Milvus, endpoint URL for custom providers).', max_length=512),
        ),
    ]
