# Generated by Django 6.0.5 on 2026-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_terminatedsession_cleared_at_and_more'),
        ('mcp_connector', '0014_rename_mcp_scan_org_tier_idx_mcp_connect_organiz_29f98f_idx_and_more'),
        ('policy', '0032_alter_vectorproviderconfig_connection_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='code',
            field=models.SlugField(help_text='Unique identifier within the organization (e.g. POL001)', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='policy_org_code_unique'),
        ),
    ]
