# Generated by Django 6.0.5 on 2026-06-12 12:26

import policy.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0033_alter_policy_code_policy_policy_org_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorproviderconfig',
            name='embedding_api_key',
            field=policy.encrypted_fields.EncryptedCharField(blank=True, default='', help_text="BYOK key for the EXTERNAL embedding provider (e.g. OpenRouter / OpenAI-compatible), used when embedding_model routes through litellm rather than the vector DB's own inference. Encrypted at rest via Fernet; only materialised in-process when building the Redis bundle. Falls back to gateway-environment credentials when empty.", max_length=512),
        ),
    ]
