# Generated by Django 6.0.5 on 2026-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0034_vectorproviderconfig_embedding_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorproviderconfig',
            name='reranker_model',
            field=models.CharField(blank=True, default='', help_text="Per-org reranker model (e.g. Pinecone-hosted 'bge-reranker-v2-m3'). When set, retrieved documents are reranked by the provider's hosted rerank API before guardrail scoring. Empty disables reranking.", max_length=128),
        ),
        migrations.AlterField(
            model_name='vectorproviderconfig',
            name='provider_type',
            field=models.CharField(choices=[('pinecone', 'Pinecone'), ('milvus', 'Milvus'), ('chroma', 'Chroma'), ('custom', 'Custom')], help_text='Vector database provider (pinecone, milvus, custom).', max_length=32),
        ),
    ]
