# Generated by Django 6.0.5 on 2026-07-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_userprofile_is_platform_operator_and_more'),
        ('mcp_connector', '0017_alter_mcpserverregistration_default_scan_action'),
        ('policy', '0038_seed_mcp_detector_policies_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServerPolicyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='True = this policy applies to this server; False = excluded from this server.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_server_policy_states', to='auth_api.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_states', to='policy.policy')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_states', to='mcp_connector.mcpserverregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'server'], name='policy_mcps_organiz_582b4b_idx')],
                'unique_together': {('server', 'policy')},
            },
        ),
        migrations.CreateModel(
            name='MCPServerRuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='True = this rule runs on this server; False = skipped for this server.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_server_rule_states', to='auth_api.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_states', to='policy.rule')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_states', to='mcp_connector.mcpserverregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'server'], name='policy_mcps_organiz_242f52_idx')],
                'unique_together': {('server', 'rule')},
            },
        ),
    ]
