# Generated by Django 6.0.5 on 2026-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0039_mcpserverpolicystate_mcpserverrulestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorcollectionpolicy',
            name='vector_db_type',
            field=models.CharField(choices=[('pinecone', 'Pinecone'), ('milvus', 'Milvus'), ('chroma', 'Chroma'), ('custom', 'Custom')], default='pinecone', max_length=32),
        ),
    ]
