# Generated by Django 6.0.3 on 2026-03-28 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0006_unique_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('input_policy', models.JSONField(blank=True, default=dict, help_text='Input guardrail policy (PII redaction, injection blocking, etc.)')),
                ('output_policy', models.JSONField(blank=True, default=dict, help_text='Output guardrail policy (adherence, relevancy, etc.)')),
                ('is_default', models.BooleanField(default=False, help_text='If true, automatically applied to newly registered MCP servers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MCPServerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(help_text='MCP server endpoint URL')),
                ('transport', models.CharField(choices=[('streamable-http', 'Streamable HTTP'), ('sse', 'SSE'), ('stdio', 'Stdio'), ('websocket', 'WebSocket')], default='streamable-http', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('contextforge_server_id', models.CharField(blank=True, default='', help_text='ID assigned by ContextForge after registration', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='auth_api.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
