# Generated by Django 6.0.3 on 2026-03-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_unique_user_email'),
        ('mcp_connector', '0002_control_plane'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcpevent',
            new_name='mcp_connect_organiz_b15f69_idx',
            old_name='mcp_connect_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpevent',
            new_name='mcp_connect_decisio_a44550_idx',
            old_name='mcp_connect_decisio_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpevent',
            new_name='mcp_connect_tool_na_bec9e0_idx',
            old_name='mcp_connect_tool_na_idx',
        ),
        migrations.AddField(
            model_name='guardrailprofile',
            name='mcp_server',
            field=models.ForeignKey(blank=True, help_text='Optional: bind this profile to a specific MCP server', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail_profiles', to='mcp_connector.mcpserverregistration'),
        ),
        migrations.AddField(
            model_name='guardrailprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_profiles', to='auth_api.organization'),
        ),
    ]
