# Generated by Django 6.0.3 on 2026-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_connector', '0003_rename_mcp_connect_organiz_idx_mcp_connect_organiz_b15f69_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserverregistration',
            name='args',
            field=models.JSONField(blank=True, default=list, help_text='Command arguments for stdio transport as a JSON array'),
        ),
        migrations.AddField(
            model_name='mcpserverregistration',
            name='command',
            field=models.CharField(blank=True, default='', help_text='Executable command for stdio transport (e.g. npx, python, node)', max_length=512),
        ),
        migrations.AddField(
            model_name='mcpserverregistration',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='Environment variables for stdio transport as a JSON object'),
        ),
        migrations.AlterField(
            model_name='mcpserverregistration',
            name='url',
            field=models.URLField(blank=True, default='', help_text='MCP server endpoint URL (required for http/sse/websocket, blank for stdio)'),
        ),
    ]
