# Generated by Django 6.0.3 on 2026-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_unique_user_email'),
        ('mcp_connector', '0004_mcpserverregistration_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserverregistration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='mcpserverregistration',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_server_name'),
        ),
    ]
