# Generated by Django 6.0.5 on 2026-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_connector', '0013_mcp_scan_control_action'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcpscancontrol',
            new_name='mcp_connect_organiz_29f98f_idx',
            old_name='mcp_scan_org_tier_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpscancontrol',
            new_name='mcp_connect_server__9fb087_idx',
            old_name='mcp_scan_srv_tool_idx',
        ),
        migrations.AlterField(
            model_name='mcpscancontrol',
            name='action',
            field=models.CharField(choices=[('inherit', 'Inherit from server/tool default'), ('monitor', 'Monitor (detect + tag, allow)'), ('redact', 'Redact'), ('block', 'Block')], default='inherit', help_text="Enforcement action for THIS tier+direction+scope row, independent per tier. 'inherit' defers to MCPToolRegistration.scan_action then MCPServerRegistration.default_scan_action then 'monitor' (safe observe-only default). Precedence within a request: block > redact > monitor; a Tier-1 block short-circuits Tier-2 (Bedrock never runs).", max_length=8),
        ),
        migrations.AlterField(
            model_name='mcpscancontrol',
            name='key_path',
            field=models.CharField(blank=True, default='', help_text='Dot path (e.g. arguments.email) or simple key name for key_path mode.', max_length=512),
        ),
        migrations.AlterField(
            model_name='mcpscancontrol',
            name='priority',
            field=models.IntegerField(default=100, help_text='Higher wins within the same scope_type + tier + direction.'),
        ),
        migrations.AlterField(
            model_name='mcpscancontrol',
            name='strict_mode',
            field=models.CharField(choices=[('strict', 'Strict (fail closed)'), ('fail_open', 'Fail open (degraded pass)')], default='fail_open', help_text='Tier-2 degradation behaviour when Bedrock is unavailable.', max_length=16),
        ),
        migrations.AlterField(
            model_name='mcpscancontrol',
            name='tool_name',
            field=models.CharField(blank=True, default='', help_text='Required when scope_type=tool; must match MCPToolRegistration.tool_name.', max_length=255),
        ),
    ]
