# Generated by Django 6.0.5 on 2026-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_connector', '0016_mcpevent_decision_scan_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserverregistration',
            name='default_scan_action',
            field=models.CharField(choices=[('tag', 'Tag only'), ('redact', 'Redact'), ('block', 'Block')], default='redact', max_length=8),
        ),
    ]
