# Generated by Django 6.0.5 on 2026-06-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0003_orgueba_scanner_graduation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikeyriskassessment',
            new_name='module2_api_gateway_ee42c6_idx',
            old_name='module2_api_gateway_7f0e2a_idx',
        ),
        migrations.AlterField(
            model_name='playbook',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='[{action: "kill_switch", params: {...}}, {action: "notify_webhook", ...}]'),
        ),
    ]
