# Generated by Django for Module 3 Cosign signature_digest length.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module3", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelartifact",
            name="signature_digest",
            field=models.TextField(blank=True),
        ),
    ]
